[package]
name = "bpf-program-template"
version = "0.1.0"
edition = "2018"
license = "WTFPL"
publish = false

[dependencies]
solana-program = "=1.7.11"
thiserror = "1.0.24"
arrayref = "0.3.6"

[lib]
crate-type = ["cdylib", "lib"]
